"""added relation_type column

Revision ID: 93cb8c3d97ca
Revises: efb17bbdead1
Create Date: 2026-08-16 23:39:01.895034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '93cb8c3d97ca'
down_revision: Union[str, Sequence[str], None] = 'efb17bbdead1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watched_folders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('folder_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folder_path')
    )
    op.add_column('file_relationships', sa.Column('relation_type', sa.String(), server_default='semantic', nullable=False))
    op.drop_column('files', 'state')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('state', sa.VARCHAR(length=20), server_default=sa.text("'scheduled'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('file_relationships', 'relation_type')
    op.drop_table('watched_folders')
    # ### end Alembic commands ###
