"""genesis migration

Revision ID: ecca7b879961
Revises: 
Create Date: 2026-06-20 16:46:17.090119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecca7b879961'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

op.execute("CREATE EXTENSION IF NOT EXISTS vector")

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_index('files_path_hash_idx', 'files', ['file_path', 'file_hash'], unique=False)
    op.create_index('files_tags_idx', 'files', ['tags'], unique=False, postgresql_using='gin')
    op.create_table('file_content',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('keyword_tokens', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', content_text)", persisted=True), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('content_embedding_idx', 'file_content', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('content_fts_idx', 'file_content', ['keyword_tokens'], unique=False, postgresql_using='gin')
    op.create_table('file_relationships',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_file_id', sa.UUID(), nullable=False),
    sa.Column('target_file_id', sa.UUID(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), server_default='semantic_similarity', nullable=False),
    sa.ForeignKeyConstraint(['source_file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_file_id', 'target_file_id', name='uq_file_relationship')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_relationships')
    op.drop_index('content_fts_idx', table_name='file_content', postgresql_using='gin')
    op.drop_index('content_embedding_idx', table_name='file_content', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('file_content')
    op.drop_index('files_tags_idx', table_name='files', postgresql_using='gin')
    op.drop_index('files_path_hash_idx', table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
