"""add watched folders table

Revision ID: efb17bbdead1
Revises: ecca7b879961
Create Date: 2026-07-02 12:29:07.453901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'efb17bbdead1'
down_revision: Union[str, Sequence[str], None] = 'ecca7b879961'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watched_folders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('folder_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folder_path')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watched_folders')
    # ### end Alembic commands ###
